# -*- coding: utf-8 -*-
"""IR1 : Preprocessing AJ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FVKV502kq2XHCRcFzULGO-9d9Ex6a0f

Question 1 : Write a program for pre-processing of a text document such as stop word removal, stemming.
"""

import nltk
from nltk.corpus import stopwords
import string
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

nltk.download('punkt_tab')
nltk.download('stopwords')

def preprocess_text(text):
    words = word_tokenize(text)
    print("After Tokenization:", words)

    words = [word.lower() for word in words]
    print("After Lowercasing:", words)

    words = [word for word in words if word not in string.punctuation]
    print("After Removing the Punctuations :",words)

    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]
    print("After Stop Word Removal:", words)

    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]
    print("After Stemming:", words)

    processed_text = ' '.join(words)
    return processed_text

text = "This is a simple example to demonstrate text preprocessing, including stop word removal!! %and stemming."

processed_text = preprocess_text(text)


print("\nOriginal Text:", text)
print("Processed Text:", processed_text)

